export const Sliders = [
  {
    id: 1,
    title: "Milks and Dairies",
    image: "./img/slider/img1.webp",
    bg: "#FFFCEB",
  },
  {
    id: 2,
    title: "Milks and Dairies",
    image: "./img/slider/img2.webp",
    bg: "#FFFCEB",
  },
  {
    id: 3,
    title: "Milks and Dairies",
    image: "./img/slider/img3.webp",
    bg: "#FFFCEB",
  },
  {
    id: 4,
    title: "Milks and Dairies",
    image: "./img/slider/img4.webp",
    bg: "#FFFCEB",
  },
  {
    id: 5,
    title: "Milks and Dairies",
    image: "./img/slider/img5.webp",
    bg: "#FFFCEB",
  },
  {
    id: 6,
    title: "Milks and Dairies",
    image: "./img/slider/img6.webp",
    bg: "#FFFCEB",
  },
  {
    id: 7,
    title: "Milks and Dairies",
    image: "./img/slider/img7.webp",
    bg: "#FFFCEB",
  },
]

/**Products */

export const Products = [
  {
    id: 1,
    title: "Himalaya Softness & Shine Daily Care 2-In-1 Shampoo Conditions Hair, Making It Smooth & Shiny -400 ml",
    niceName: "himalaya soft conditions hair",
    slug:'soundpeats-watches-waterproof',
    imageUrl: "./img/products/beautycare.png",
    category: "beauty",
    rating: 4,
    price: 12,
    discount: 5,
    stock: 50,
    deal: true,
    dealends: 5,
    tag: "hot",
    bg:"#f74b81",
    brand: "himalaya",
    featured: true,
    views: 1,
    sales: 1,
    images: [
       "/images/products/digitalcamera.png",
    ]
  },
  {
    id: 2,
    title: "Handheld Barcode Scanner 1D 2D QR Code Scanner 2.4G Wireless & USB Wired Bar Code Compatible with Windows Mac Linux for Supermarket Retail Library Logistics Warehous",
    niceName: "barcode-scanner usb-scanner",
    slug:'soundpeats-watches-waterproof',
    imageUrl: "./img/products/scanner.png",
    category: "accessories",
    rating: 4,
    price: 120,
    discount: 110,
    stock: 20,
    deal: false,
    dealends: 6,
    tag: "new",
    bg: "#3bb77e",
    brand: "sony",
    featured: true,
    views: 21,
  },
  {
    id: 3,
    title: "Seeds of Change Organic Quinoa, Brown, & Red Rice",
    niceName: "brown organization riceseed",
    slug:'soundpeats-watches-waterproof',
    imageUrl: "./img/products/catshoes.png",
    category: "shoes",
    rating: 4,
    price: 15,
    discount: 30,
    stock: 40,
    deal: false,
    dealends: false,
    tag: "hot",
    bg:"#f74b81",
    brand: "samsung",
    featured: false,
    views: 22,
  },
  {
    id: 4,
    title: "Apple MacBook Pro 16 M1 Retina XDR Laptop",
    niceName: "apple macOS Pro 16 M1 Retina",
    slug:'soundpeats-watches-waterproof',
    imageUrl: "./img/products/imac.png",
    category: "computer",
    rating: 3.5,
    price: 16900,
    discount: 13900,
    stock: 10,
    deal: true,
    dealends: 3,
    tag: "new",
    bg: "#3bb77e",
    brand: "apple",
    featured: false,
    views: 23,
    images: [
      "/images/products/imac1.png",
      "/images/products/imac2.png",
      
   ],
  },
  {
    id: 5,
    title: "50 Inch 4K UHD Smart LED TV, HDR Crystal Processor 4K With Tizen OS, 60 Hz Refresh rates and Built-In Receiver Model (2021). UA50AU7000UXUM Black",
    niceName: "smart led hdr processor",
    slug:'soundpeats-watches-waterproof',
    imageUrl: "./img/products/led.png",
    category: "led",
    rating: 4,
    price: 3500,
    discount: 1800,
    stock: 5,
    deal: true,
    dealends: 2,
    tag: "best sell",
    bg: "#f59758",
    brand: "samsung",
    featured: false,
    views: 24,
    images: [
      "/images/products/led1.png",
      
      
   ],
  },
  {
    id: 6,
    title: "Huawei Watch Gt 2 Pro Smartwatch, 1.39 Amoled Hd Touchscreen, 2-Week Battery Life, Gps And Glonass,100 Plus Workout Modes, Bluetooth Calling, Heartrate Monitoring, Gray Brown Nebula, Gray GT 46mm",
    niceName: "huawei device with Bluetooth",
    slug:'soundpeats-watches-waterproof',
    imageUrl: "./img/products/bluewatch.png",
    category: "smartwatch",
    rating: 5,
    price: 739,
    discount: 739,
    stock: 8,
    deal: true,
    dealends: 3,
    tag: "sale",
    bg: "#67bcee",
    brand: "huawei",
    featured: true,
    views: 15,
  },
  {
    id: 7,
    title: "SoundPEATS Watch 2 Smartwatch SpO2 with 12 Sports Modes Fitness Tracker Heart Rate Sleep Quality Monitor IP68 Waterproof Smart Watches Compatible with iPhone Android Phones, Smart watch for Men Women",
    niceName: "soundpeats watches waterproof",
    slug:'soundpeats-watches-waterproof',
    imageUrl: "./img/products/graywathch.png",
    category: "smartwatch",
    rating: 4,
    price: 149,
    discount: 111,
    stock: 40,
    deal: false,
    dealends: false,
    tag: "new",
    bg: "#3bb77e",
    brand: "SoundPEATS",
    featured: true,
    views: 7,
    images: [
      "/images/products/graywathch1.png",
      "/images/products/graywathch2.png", 
   ],
  },
  {
    id: 8,
    title: "Lenovo HD200 Bluetooth Headphone with Microphone - Black",
    niceName: "Lenovo top collection",
    slug:'lenovo-top-collection',
    imageUrl: "./img/products/headphone.png",
    category: "headphone",
    rating: 5,
    price: 85,
    discount: 80,
    stock: 20,
    deal: false,
    dealends: false,
    tag: "new",
    bg: "#3bb77e",
    brand: "lenovo",
    featured: false,
    views: 4,
    images: [
      "/images/products/headphone1.png",
      "/images/products/headphone2.png",
      "/images/products/headphone3.png",
      
      
   ],

  },
  {
    id: 9,
    title: "SAMSUNG Galaxy A73 5G Android Smartphone, 256 GB, 8 GB RAM, Dual Sim Mobile Phone, Awesome Mint (UAE Version)",
    niceName: "Android Smartphone 5G",
    imageUrl: "./img/products/androidphone.png",
    category: "smartphone",
    rating: 4,
    price: 1768,
    discount: 1500,
    stock: 6,
    deal: false,
    dealends: false,
    tag: "new",
    bg: "#3bb77e",
    brand: "samsung",
    featured: false,
    views: 3,
    images: [
      "/images/products/androidphone1.png",
      "/images/products/androidphone2.png",
   ]


  },
  {
    id: 10,
    title: "New Apple iPhone 14 Pro (512 GB) - Gold",
    niceName: "Apple pro 13 plus",
    imageUrl: "./img/products/iphone.png",
    category: "smartphone",
    rating: 4,
    price: 6000,
    discount: 5500,
    stock: 1,
    deal: true,
    dealends: 4,
    tag: "hot",
    bg:"#f74b81",
    brand: "apple",
    featured: false,
    views: 50,
    images: [
      "/images/products/iphone1.png",
      "/images/products/iphone2.png",
      "/images/products/iphone3.png",
      "/images/products/iphone4.png",
   ]
  },
  {
    id: 11,
    title: "Clothing Set of Washables",
    niceName: "Portable Package of Polyster",
    imageUrl: "./img/slider/img3.webp",
    category: "beauty",
    rating: 4,
    price: 6000,
    discount: 5500,
    stock: 1,
    deal: true,
    dealends: 4,
    tag: "hot",
    bg:"#f74b81",
    brand: "apple",
    featured: false,
    views: 28,
    images: [
      "/images/products/iphone1.png",
      "/images/products/iphone2.png",
      "/images/products/iphone3.png",
      "/images/products/iphone4.png",
   ]
  },
  {
    id: 12,
    title: "Accessories Set of Products",
    niceName: "All in One Collection",
    imageUrl: "./img/slider/img7.webp",
    category: "accessories",
    rating: 4,
    price: 6000,
    discount: 5500,
    stock: 1,
    deal: true,
    dealends: 4,
    tag: "hot",
    bg:"#f74b81",
    brand: "apple",
    featured: false,
    views: 22,
    images: [
      "/images/products/iphone1.png",
      "/images/products/iphone2.png",
      "/images/products/iphone3.png",
      "/images/products/iphone4.png",
   ]
  },
  {
    id: 13,
    title: "Beauty Products top Brand",
    niceName: "Top Rated Made High Quality",
    slug: 'top-rated-products',
    imageUrl: "./img/slider/img4.webp",
    category: "beauty",
    rating: 4,
    price: 6000,
    discount: 5500,
    stock: 1,
    deal: true,
    dealends: 4,
    tag: "hot",
    bg:"#f74b81",
    brand: "apple",
    featured: false,
    views: 28,
    sales: 31,
    images: [
      "/images/products/iphone1.png",
      "/images/products/iphone2.png",
      "/images/products/iphone3.png",
      "/images/products/iphone4.png",
   ]
  },

  {
    id: 14,
    title: "Leather Shoes for foggy",
    niceName: "leather foggy shoes",
    slug: 'top-rated-products',
    imageUrl: "./img/slider/img3.webp",
    category: "shoes",
    rating: 4,
    price: 6000,
    discount: 5500,
    stock: 1,
    deal: true,
    dealends: 4,
    tag: "hot",
    bg:"#f74b81",
    brand: "apple",
    featured: false,
    views: 28,
    sales: 20,
    images: [
      "/images/products/iphone1.png",
      "/images/products/iphone2.png",
      "/images/products/iphone3.png",
      "/images/products/iphone4.png",
   ]
  },
  {
    id: 15,
    title: "Top Trendy winter collection",
    niceName: "top-trendy-seasons-collection",
    slug: 'top-trendy-seasons-collection',
    imageUrl: "./img/products/digitalcamera.png",
    category: "beauty",
    rating: 4,
    price: 6000,
    discount: 5500,
    stock: 1,
    deal: true,
    dealends: 4,
    tag: "hot",
    bg:"#f74b81",
    brand: "apple",
    featured: false,
    views: 28,
    sales: 20,
    images: [
      "/images/products/iphone1.png",
      "/images/products/iphone2.png",
      "/images/products/iphone3.png",
      "/images/products/iphone4.png",
   ]
  },
  {
    id: 16,
    title: "Digital Movies Maker Camera",
    niceName: "top-trendy-seasons-collection",
    slug: 'top-trendy-seasons-collection',
    imageUrl: "./img/products/digitalcamera.png",
    category: "camera",
    rating: 4,
    price: 6000,
    discount: 5500,
    stock: 1,
    deal: true,
    dealends: 4,
    tag: "hot",
    bg:"#f74b81",
    brand: "apple",
    featured: false,
    views: 28,
    sales: 20,
    images: [
      "/images/products/iphone1.png",
      "/images/products/iphone2.png",
      "/images/products/iphone3.png",
      "/images/products/iphone4.png",
   ]
  },
]